package org.example.services;

import lombok.NoArgsConstructor;
import org.example.exceptions.FileException;
import org.example.exceptions.NoSubmissionException;
import org.example.models.Association;
import org.example.models.Student;
import org.example.models.Submission;

import java.io.*;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipException;
import java.util.zip.ZipFile;

@NoArgsConstructor
public class ImportService {

    /**
     * Import data as downloaded from Brightspace to the application
     *
     * @param zipFile .zip file containing student submissions
     * @param csvFile .csv file containing a list of all students
     * @return List of association pairs < Student, Submission >. They should be further used for
     * saving in the database.
     * @throws NoSubmissionException if a directory does not contain any submissions
     * @throws ZipException if the zip file behaves unexpectedly
     */
    public List<Association> importData(File zipFile, File csvFile) throws NoSubmissionException, ZipException, FileException {
        List<Student> studentList = processCsv(csvFile);
        List<Submission> submissionList = extractZip(zipFile);
        return associate(studentList, submissionList);
    }

    /**
     * Associates students to their submissions, based on their full name.
     * NOTE: this may have unexpected behaviour in the situation where two students with the
     * exact same name are enrolled in the same edition of the same course.
     *
     * @param students List of students extracted from the .csv file
     * @param submissions List of submissions extracted from the .zip file
     */
    private List<Association> associate(List<Student> students, List<Submission> submissions) {
        List<Association> associations = new ArrayList<>();
        for (Submission current : submissions) {
            Optional<Student> item = students.stream()
                .filter(s -> s.getStudentName().equals(current.getStudentName()) &&
                s.getGroupName().equals(current.getGroupName()))
                .findFirst();
            item.ifPresent(student -> associations.add(new Association(student, current)));
        }
        return associations;
    }

    /**
     * Extracts data from the zip file containing student submissions, retrieved from Brightspace.
     *
     * @param zipFile .zip file containing student submissions
     * @return List of Submission objects, containing submission data
     * @throws NoSubmissionException if a directory does not contain any submissions
     * @throws ZipException if the zip file behaves unexpectedly
     */
    private List<Submission> extractZip(File zipFile) throws NoSubmissionException, ZipException {
        List<Submission> submissionList = new ArrayList<>();
        try (ZipFile file = new ZipFile(zipFile)) {
            Enumeration<? extends ZipEntry> entries = file.entries();
            Set<String> directories = new HashSet<>();
            while(entries.hasMoreElements()) {
                ZipEntry entry = entries.nextElement();
                String name = entry.getName();
                /* This if statement should not be entered when working with zip files generated by
                Brightspace. However, it may be entered when using zip files from other sources.
                If the export tool from Brightspace changes the way it generates zip files, this
                place should be the first place to look for eventual errors. */
                if(entry.isDirectory()) {

                    InputStream inputStream = file.getInputStream(entry);
                    File currentEntry = new File(System.getProperty("java.io.tmpdir") + "/" + entry.getName());
                    OutputStream outputStream = new FileOutputStream(currentEntry);
                    outputStream.write(inputStream.readAllBytes());

                    inputStream.close();
                    outputStream.close();

                    Submission submission = processFileName(name);
                    File submittedFile = Objects.requireNonNull(currentEntry.listFiles())[0];
                    InputStream submittedStream = new FileInputStream(submittedFile);
                    submission.setSubmittedFile(submittedStream.readAllBytes());
                    submissionList.add(submission);
                } else {
                    /* extract directory. Functionality can be further extended by checking for
                    different directory names, and further processing files from that directory. */
                    int lastIndex = name.lastIndexOf('/');
                    if(lastIndex != -1) {
                        String dirName = name.substring(0, lastIndex);
                        directories.add(dirName);

                        InputStream inputStream = file.getInputStream(entry);

                        Submission submission = processFileName(dirName);
                        submission.setSubmittedFile(inputStream.readAllBytes());
                        submissionList.add(submission);
                        inputStream.close();
                    }
                }
            }
        } catch (IOException e) {
            throw new ZipException("Zip file could not be read.");
        } catch (NullPointerException e) {
            throw new NoSubmissionException("Not all directories contain submissions. " +
                    "Please ensure all submissions are registered before trying to upload the zip file. " +
                    "If this is not the case, please use the manual upload functionality.");
        }
        return submissionList;
    }

    /**
     * Extracts data from a csv file containing a list of all students, retrieved from Brightspace
     *
     * @param csvFile .csv file containing a list of all students
     * @return List of Student objects, containing student data
     */
    private List<Student> processCsv(File csvFile) throws FileException {
        if(!csvFile.exists())
            throw new FileException("csv file appears to not exist. Please try again");
        List<Student> students = new ArrayList<>();
        try (Scanner scanner = new Scanner(csvFile)) {
            scanner.nextLine();
            while(scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] data = line.split(",");
                String studentNo = data[0];
                String username = data[1];
                String studentName = data[3] + " " + data[2];
                String email = data[4];
                String groupCategory = data[5];
                String groupName = data[6].replaceAll("\n", "");
                Student student = new Student(studentNo, username, studentName, email, groupCategory, groupName);
                students.add(student);
            }
        } catch (FileNotFoundException e) {
            throw new FileException("Csv file could not be processed");
        }
        return students;
    }

    /**
     * Processes a submission directory name, parsing all data according to the format
     * defined by the Brightspace export tool.
     *
     * @param name The name of a directory containing student submissions
     * @return a Submission object, containing all data
     */
    private Submission processFileName(String name) {
        String[] split = name.split("-");
        String groupNo = split[0];
        String assignmentNo = split[1].substring(0, split[1].length() - 1);
        String groupName = split[2].substring(1, split[2].length() - 1);
        String studentName = split[3].substring(1, split[3].length() - 1);
        String date = split[4].substring(1);
        return new Submission(groupNo, assignmentNo, groupName, studentName, date);
    }
}
